DINT-56: abandonCart event
adobe/magento-storefront-event-collector pull request #100
Opened 2022-03-01 21:56 UTC by aniham

changes:
- update sdk version(need new `abandonCart` event)
- add aep + snowplow handlers for `abandonCart`
- remove references to `eventForwarding.snowplow` (next version of sdk will replace it with `eventForwarding.commerce`)

2022-03-01 23:19 UTC, jekelly-adobe commented on src/handlers/shoppingCart/abandonCartAEP.ts
> +            checkouts: {
`checkouts` should be `cartAbandons`

2022-03-01 23:19 UTC, jekelly-adobe commented on src/handlers/shoppingCart/abandonCartAEP.ts
> +                cartId: shoppingCartContext.id ?? "1",
`cartId` should be `cartID`

2022-03-01 23:23 UTC, jekelly-adobe requested changes
A few field names in the XDM payload need changing

2022-03-02 15:25 UTC, jekelly-adobe approved these changes

2022-03-02 15:45 UTC, grahamcrackers commented on src/handlers/shoppingCart/abandonCartAEP.ts
> +                ID: shoppingCartContext.id,
should it be `id` instead of `ID`? just to keep formatting consistancy?

2022-03-02 16:04 UTC, merged