DINT-246: Configure alloy with cookie restrictions.
adobe/magento-storefront-event-collector pull request #139
Opened 2022-05-24 19:26 UTC by admanesachin

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2022-05-24 19:44 UTC, aniham requested changes
@admanesachin looks great overall!!!!

i had some style etc comments AND also can you please add proper documentation to the readme explaining how the cookie is used, how to set, and so on?

2022-05-24 19:44 UTC, aniham commented on src/alloy.ts
>              debugEnabled: true,
i know this isn't part of your ticket but i noticed it and we are so close to release - let's remove the `debugEnabled: true`

2022-05-24 19:44 UTC, aniham commented on src/alloy.ts
> +    const mg_dnt_cookie = document.cookie.indexOf("mg_dnt") !== -1;
please rename to `doNotTrackCookie`

2022-05-24 19:44 UTC, aniham commented on src/alloy.ts
> +                    general: consent,
i'd get rid of the `consent` variable altogether and change this to `general: doNotTrackCookie ? 'out' : 'in'`

2022-05-24 19:44 UTC, aniham commented on src/alloy.ts
> +setInterval(setConsent, 1000);
i understand why you're doing this but a first time reader might be confused - could you please add a comment explaining why we're retrying?

2022-05-24 19:46 UTC, aniham commented
@admanesachin also looks like tests and/or linter is failing

you can repro locally by running `npm run test` `npm lint:fix` `npm format:fix` - additionally, can you either add a note to the readme or a git hook for people to do this before submitting PRs - seems to be a common problem when people forget to do this

2022-05-25 14:47 UTC, aniham commented on src/alloy.ts
> +                    general: consent,
@admanesachin i just re-read this - this doesn't meet the requirements that shankar described right?

a shopper is going to be *opted in* by default - we want them to be *opted out* by default

the `dnt` cooking will not work at all in that way. the whole point of it is that it's an opt out cookie, not an opt in cookie. can you start a convo with shankar in the dev channel on this?

2022-05-25 18:00 UTC, admanesachin commented on src/alloy.ts
>              debugEnabled: true,
Fixed.

2022-05-25 18:00 UTC, admanesachin commented on src/alloy.ts
> +setInterval(setConsent, 1000);
Added comment.

2022-05-26 13:27 UTC, aniham approved these changes

2022-05-26 15:26 UTC, merged