test: add tests for handlers
adobe/magento-storefront-event-collector pull request #20
Opened 2021-03-31 19:45 UTC by bradgarropy

## Description

Add tests for event handlers.

## Related Issue

N/A

## Motivation and Context

Increases test coverage!

## How Has This Been Tested?

Tested with the tests I just wrote!

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2021-04-08 18:09 UTC, evargast requested changes

2021-04-08 18:09 UTC, evargast commented on tests/contexts/product.test.ts
> +            updatedAt: "01/01/2021",
This seems too static and fragile, I'm not too comfortable with these tests 😓

2021-04-08 18:09 UTC, evargast commented on tests/contexts/product.test.ts
> +            updatedAt: "01/01/2021",
Could we make them something like:

```javascript 
expect(ctx).toEqual({
    data: { ...mockProductData }
    schema: PRODUCT_SCHEMA_URL
});
```

Or using `.toMatchSchema` and having the JSON schemas listed somewhere

I think having the hard-coded JSONs in every test is not very robust / dynamic.

2021-04-08 18:09 UTC, evargast commented on tests/contexts/product.test.ts
> +            updatedAt: "01/01/2021",
Same comment for all tests, they all seem to be hardcoded json comparisons - lets maybe chat / brainstorm on other testing strategies through slack or a bjns call ?

2021-04-08 19:23 UTC, bradgarropy commented on tests/contexts/product.test.ts
> +            updatedAt: "01/01/2021",
Happy to change this! I was just trying to move fast and get _some_ kind of validation in there.
For starters I'll move them out to `mocks`, does that work?

2021-04-08 19:26 UTC, evargast commented on tests/contexts/product.test.ts
> +            updatedAt: "01/01/2021",
Sure! And lets make sure we use the PRODUCT_SCHEMA_URL instead of hardcoding it 🥳

2021-04-08 20:14 UTC, bradgarropy commented on tests/contexts/product.test.ts
> +            updatedAt: "01/01/2021",
Done! Thanks for the candid feedback 👍🏼

2021-04-08 21:32 UTC, abrhim approved these changes

2021-04-09 15:06 UTC, evargast approved these changes
beautiful, thank you!

2021-04-09 16:37 UTC, merged