Dint 54 - adding AEP addToCart event
adobe/magento-storefront-event-collector pull request #90
Opened 2022-02-08 19:18 UTC by grahamcrackers

## Description

Adding addToCart event for AEP

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2022-02-08 20:47 UTC, aniham commented
@grahamcrackers 

can you do the following:
`npm run format:fix`
`npm run test`

format fix should take care of linting issues, test should tell you if anything else is off

2022-02-08 22:03 UTC, aniham requested changes
@grahamcrackers - this looks great for the most part - a few minor comments and questions AND:

we need to start adding unit tests for these. another thing i might have not communicated well, but my hope was that as we start adding these cases, unit tests will come with that. could you please add here and if not already in all the jira stories, could you change the acceptance criteria in the jira stories to include unit tests?

2022-02-08 22:03 UTC, aniham commented on src/handlers/product/addToCartAEP.ts
> +        currencyCode: item.prices.price?.currency ?? undefined,
i think this would auto be `undefined` without the `?? undefined`

2022-02-08 22:03 UTC, aniham commented on src/handlers/product/addToCartAEP.ts
> +        priceTotal: item.prices.price.value,
you check `prices.price?` on the line below but not here - in what circumstances can this be undef?

2022-02-08 22:03 UTC, aniham commented on src/handlers/product/addToCartAEP.ts
> +const aepHandler = (event: Event): void => {
i know we do a terrible job of documenting stuff. not requesting a change here, but it would set a good example if we start adding more comments on what/how we handle things - or we can just fix documentation in a big sweep later on

2022-02-10 18:33 UTC, grahamcrackers commented on src/handlers/product/addToCartAEP.ts
> +const aepHandler = (event: Event): void => {
I think once a file is touched, if it doesn't have at least some comments on it, we should add them. Even if they are basic ones.

2022-02-11 19:39 UTC, grahamcrackers commented on src/handlers/product/addToCartAEP.ts
> +        priceTotal: item.prices.price.value,
the [types coming from the ShoppingCart in the sdk](https://github.com/adobe/magento-storefront-events-sdk/blob/e8d6a2505495d6c3f1adf1e6be726ca624a38a4d/src/types/schemas/shoppingCart.ts#L18) have value as required and currency as optional

2022-02-11 21:28 UTC, aniham requested changes

2022-02-11 21:28 UTC, aniham commented on .gitignore
> +.DS_Store
needs new line

2022-02-11 21:28 UTC, aniham commented on src/handlers/product/addToCartAEP.ts
> +        priceTotal: item.prices.price.value,
i  think priceTotal should be `item.prices.price?.value`

2022-02-11 21:28 UTC, aniham commented on src/types/aep/addToCart.interface.ts
> +    id?: string;
why is id optional here? great comment btw!

2022-02-11 21:28 UTC, aniham commented on src/types/aep/beaconSchema.interface.ts
> +export interface BeaconSchema {
i believe many of these fields are sent by alloy automatically and not ever sent by us - i would keep the interface here to include the fields we are actually sending *now* - and expand it in future stories if we start sending more

2022-02-11 21:28 UTC, aniham commented on src/types/aep/commerce.interface.ts
> +    _atag?: Record<string, unknown>;
same sa prev comment, atag is a legacy field that we'll never send :)

2022-02-11 21:28 UTC, aniham commented on src/types/aep/commerce.interface.ts
> +    promotionID?: string;
same

2022-02-11 23:06 UTC, grahamcrackers commented on .gitignore
> +.DS_Store
fixed

2022-02-11 23:07 UTC, grahamcrackers commented on src/types/aep/addToCart.interface.ts
> +    id?: string;
it is not required in the schema in AEP

2022-02-11 23:15 UTC, grahamcrackers commented on src/handlers/product/addToCartAEP.ts
> +        priceTotal: item.prices.price.value,
fixed in next push

2022-02-11 23:16 UTC, grahamcrackers commented on src/types/aep/beaconSchema.interface.ts
> +export interface BeaconSchema {
i've removed all the unnecessary fields that I originally added. I agree that we only add what each subsequent event uses in it's payload

2022-02-11 23:17 UTC, grahamcrackers commented on src/types/aep/commerce.interface.ts
> +    promotionID?: string;
removed

2022-02-11 23:56 UTC, merged