Dint 57
adobe/magento-storefront-event-collector pull request #99
Opened 2022-03-01 20:34 UTC by grahamcrackers

## Description

Adding shoppingCartView event to aep collector

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2022-03-01 20:47 UTC, aniham requested changes
@grahamcrackers good stuff!! request a few changes, looks good otherwise!

2022-03-01 20:47 UTC, aniham commented on src/types/aep/idAndValue.ts
> +// i really don't know what else to call this class, `Base` sounds way to generic
i don't see this class as a useful abstraction and think we should do it this way:

https://github.com/adobe/magento-storefront-event-collector/blob/main/src/types/aep/commerce.ts#L43-L45

2022-03-01 20:47 UTC, aniham commented on src/handlers/shoppingCart/viewAEP.ts
> +    }));
we should use our utils method to get these:

https://github.com/adobe/magento-storefront-event-collector/blob/main/src/utils/aep/productListItems.ts

2022-03-01 20:47 UTC, aniham commented on src/types/aep/commerce.ts
> +import { ProductListAdds, ProductListViews } from "./addToCart";
`ProductListAdds` is specific to `Commerce` - it's unnecessary and confusing to split it into a separate file

2022-03-01 20:47 UTC, aniham commented on src/handlers/shoppingCart/viewAEP.ts
> +        commerce: {
i think we need a cartId + other cart info in the schema here, right?

2022-03-02 00:14 UTC, aniham commented on src/handlers/shoppingCart/viewAEP.ts
> +            },
note to @grahamcrackers + @jekelly-adobe - i know this is wrong based on the discussion that happened 5 minutes ago, but i think it's ok to merge - i've already made the changes to my pr and waiting on a test to go through. when graham merges, i can pull down his stuff too and edit this one field (requires a schema edit too)

2022-03-02 00:15 UTC, aniham approved these changes

2022-03-02 00:16 UTC, grahamcrackers commented on src/handlers/shoppingCart/viewAEP.ts
> +            },
👍

2022-03-02 00:16 UTC, merged